[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
noirwire_contracts = "6vySUQGyA67t7UtXKuauvn5QHZscj9fG26SZegq7UnCf"
zk_pool = "Hza5rjYmJnoYsjsgsuxLkyxLoWVo6RCUZxCB3x17v8qz"

[programs.devnet]
noirwire_contracts = "6vySUQGyA67t7UtXKuauvn5QHZscj9fG26SZegq7UnCf"
zk_pool = "Hza5rjYmJnoYsjsgsuxLkyxLoWVo6RCUZxCB3x17v8qz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
